### PR TITLE
SharedMem

### PR DESCRIPTION
**Pull request by baovu-unikie**
Implementation of shared mem with test cases.
- Timeout is set = 3 seconds.
- Setup environment
```bash
./environment_setup
```
- Build & test (test takes about 200~300 seconds (669 test cases) to finish)
```bash
./build_and_test.sh
```
> Note: If run `bazel test //test:test` alone and not using `./build_and_test.sh` script, copy`ipc_send` and `ipc_receive` binaries to `data` directory.

- Binary files and test's log are in `build` directory.
- Test coverage report in `html` directory
- Info about usage:
```bash
./ipc_send -h
./ipc_receive -h
```

### CODE REVIEW

**Review by RomainChaumontet — APPROVED** [review]
Really good work!!

**Review by Aleksandras-V — COMMENTED** [review]
Your code looks fine,
But I launched your sender and it tells me that the data was sent, but to where ?
I didn't launched any receiver.
Capture

**Review by Aleksandras-V — COMMENTED** [review]
When I launch only the receiver it would be nice to have a timeout error kind of message instead of this which is not familliar for the user
Capture
.

**Comment by baovu-unikie** [comment]
> Your code looks fine, But I launched your sender and it tells me that the data was sent, but to where ? I didn't launched any receiver. Capture

Thanks for pointing out. I forgot to check if data is read by receiver or not. Fixed.


> When I launch only the receiver it would be nice to have a timeout error kind of message instead of this which is not familliar for the user Capture .

Also fixed.

**Review by KinhTruongUnikie — APPROVED** [review]

**Pull request merged**
